---
# check to see if VM exists before cloning - nutanix allows duplicate names but
# we dont
- name: Check to see if VM exists in prism central
  mod_nutanix:
    user: "{{ nutanix_user }}"
    password: "{{ nutanix_pw }}"
    central_addr: "{{ central_addr }}"
    port: "{{ nutanix_port }}"
    vm: "{{ vm_name }}"
    action: get_vm
  register: result

- name: debugging VM search variable
  debug:
    msg:
    - "VM search value: {{ result }}"

# removed custom conditionals for determining
# some vm customizations, time-zones, domain stuff