---

- name: find_vms_in_category.yml
  debug:
    msg:
    - "{{ category_name }}"
    - "{{ category_value }}"

- name: query Vms of a specific category
  mod_nutanix:
    user: "{{ nutanix_user }}"
    password: "{{ nutanix_pw }}"
    central_addr: "{{ central_addr }}"
    port: "{{ nutanix_port }}"
    category_name: "{{ category_name }}"
    category_value: "{{ category_value }}"
    action: find_vms_in_category
  register: category_result

- name:
  debug:
    msg:
    - "category_result: {{ category_result }}"