---

- name: find_vm.yml
  debug:
    msg:
    - "central_addr: {{ central_addr }}"
    - "vm_name: {{ vm_name }}"

- name: Check to see if VM exists in prism central
  mod_nutanix:
    user: "{{ nutanix_user }}"
    password: "{{ nutanix_pw }}"
    central_addr: "{{ central_addr }}"
    port: "{{ nutanix_port }}"
    vm: "{{ vm_name }}"
    action: query_vm_details
  register: nutanix_results
  ignore_errors: true

- name: debugging result
  debug:
    msg:
    - "Nutanix results: {{ nutanix_results }}"

- name: fail when found_vmware is defined AND 'instance' in currenct vmware_results
  set_fact:
    found_nutanix: true
  when: nutanix_results.failed == false

- name: set variable of found nutanix vm
  set_fact:
    found_nutanix: false
  when: nutanix_results.failed == true

- name: debugging conditional
  debug:
    msg:
    - "found_nutanix: {{ found_nutanix }}"
  when: found_nutanix is defined

