---


- name: fetch the host record.
  set_fact:
    host_record: "{{ lookup('nios', 'record:host', provider={'host':infoblox_host,
                                                         'username':infoblox_user,
                                                         'password':infoblox_pw },
                                               filter={'name': fqdn}) }}"

- name: set the IP address when host_record is defined
  set_fact:
    ip: "{{ host_record.ipv4addrs[0].ipv4addr }}"
  when: "'_ref' in host_record"

- name: View host record variable
  debug:
    msg:
    - "{{ host_record }}"
    - "{{ ip }}"
  when: "'_ref' in host_record"



- name: fetch the A record.
  set_fact:
    a_record: "{{ lookup('nios', 'record:a', provider={'host':infoblox_host,
                                                         'username':infoblox_user,
                                                         'password':infoblox_pw },
                                               filter={'name': fqdn}) }}"

- name: set the IP address from the A_record variable
  set_fact:
    ip: "{{ a_record.ipv4addr }}"
  when: "'_ref' in a_record"

- name: View A record variable
  debug:
    msg:
    - "A_record: {{ a_record }}"
    - "IP_A_record: {{ ip }}"
  when: "'_ref' in a_record"


- name: fetch the PTR record.
  set_fact:
    ptr_record: "{{ lookup('nios', 'record:ptr', provider={'host':infoblox_host,
                                                         'username':infoblox_user,
                                                         'password':infoblox_pw},
                                                          filter={'ptrdname': fqdn}) }}"

- name: debug ptr_record variable
  debug:
    msg:
    - "ptr_record {{ ptr_record }}"

- name: set the ptrdname and ptr_record_id variables
  set_fact:
    ptr_record_id: "{{ ptr_record._ref }}"
    ptrdname: "{{ ptr_record.ptrdname }}"
  when: "'_ref' in ptr_record"

- name: View PTR record variables
  debug:
    msg:
    - "ptrdname: {{ ptrdname }}"
  when: "'_ref' in ptr_record"

