---

- name: debug something so its ok for Dan
  debug:
    msg:
    - "here is something"
    - "client_name: {{ client_name }}"
    - "commserve: {{ commserve }}"
    - "username: {{ username }}"
    - "password: {{ password }}"

- name: test out the mod_commvault.py file
  mod_commvault:
    action: get_client_license
    client: "{{ client_name }}"
    username: "{{ commvault_user }}"
    password: "{{ commvault_pass }}"
    commserve: "{{ commserve }}"
  register: search_results

- name:
  debug:
    msg:
    - "search_results: {{ search_results }}"


