
- name: task to add VM to project
  mod_nutanix:
    user: "{{ nutanix_user }}"
    password: "{{ nutanix_pw }}"
    central_addr: "{{ central_addr }}"
    port: "{{ nutanix_port }}"
    project: "{{ business_unit }}"
    vm: "{{ vm }}"
    action: update_vm_project
  register: proj_result

- name: debug project_result task
  debug:
    msg: "Project_result: {{ proj_result.meta.metadata.project_reference }}"

- name: debug add vm to project task uuid
  debug:
    msg:
    - "task_uuid: {{ proj_result.meta.status.execution_context}}"
    - "state: {{ proj_result.meta.status.execution_context }}"
