---
- hosts: localhost
  connection: local
  gather_facts: false

# ansible-playbook playbooks/nutanix_vm_provision.yml --ask-vault-pass or --vault-password-file -e "env=test|prod request_number="
  vars_files:
  - ../group_vars/{{env}}-vault.yml
  - ../group_vars/mskey-vault.yml
  - ../group_vars/{{env}}-vars.yml

  vars:
    snow_ritm: "{{ request_number }}" # pass as --extra-var 


  roles:
  - snow_get_ritm
  - snow_close_backup # closing IP Address Assignment stage
